name: Deploy Backend to AWS

on:
  push:
    branches: [ Demo ]
    paths: [ 'Backend/**' ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Upload backend files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "Backend/*"
          target: "/home/ubuntu/backend"
          strip_components: 1
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/backend
            npm install --production
            pm2 delete backend || true
            pm2 start server.js --name backend
            pm2 save
            pm2 startup 