name: Deploy Frontend to Hostinger

on:
  push:
    branches: [ Demo ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd Frontend
          npm install --legacy-peer-deps

      - name: Build
        run: |
          cd Frontend
          npm run build

      - name: Deploy to Hostinger via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: "Frontend/dist/*"
          target: ${{ secrets.HOSTINGER_PATH }} 